devices([
#"iPhone SE (3rd generation)",
    "iPhone 14",
#   "iPhone 8 Plus",
#   "iPhone SE",
#   "iPhone X",
#   "iPad Pro (12.9-inch)",
#    "iPad Pro (12.9-inch) (6th generation)",
#   "iPad Pro (9.7-inch)",
 ])

#
languages([
"en-US"
])

localize_simulator(true)

#erase_simulator(true)

#reinstall_app(true)

# The name of the scheme which contains the UI Tests
scheme("ScreenShotTests")

# Where should the resulting screenshots be stored?
output_directory("./screenshots")

# remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

# Remove the '#' to set the status bar to 9:41 AM, and show full battery and reception. See also override_status_bar_arguments for custom options.
override_status_bar(true)

# dark mode ?
# dark_mode(false)


# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot
